---
name: johnsy.com
title: Eventuate
description: Extracts information from parkrun results pages for inclusion in reports
description_html: |
  Pete Johns (<a href="https://namedrop.io/petejohns"><em>/piːt ʤɒnz/</em></a> -
  <a href="https://pronouns.org/he">he/him/his</a>): Human being; just like you.
baseurl: /eventuate
url: https://www.johnsy.com

apple_touch_icon_sizes:
  - 57
  - 60
  - 72
  - 76
  - 114
  - 120
  - 144
  - 152

favicon_sizes:
  - 16
  - 32
  - 96
  - 128
  - 196

include:
  - icons

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
